### ISSUE TITLE
[Bug]: Invalid email format when it is correct

### ISSUE THREAD

**Issue by RomanRobotnik** [RobotnikAutomation/robotnik_email#7]
### What happened?

Sending emails fails for some types of domains.
The current check of the mail validation is no correct.
On the other hand, when one of the email recipients is not correct, the whole email is not sent.

### Relevant log output

```shell
rosservice call /smtp_manager/send_email "recipients: ['blabla@gmail.com','blabla@unitedrobotics.group','blabla@robotnik.es']
status: {id: 0, description: 'This is a test', type: '', message: 'Hello! This is a test to check if the emails can be sent via robotnik_email'}
uuid: ''
datetime: ''
files_to_upload: ['']" 
ret: 
  success: False
  message: "The email can not be sent because it is malformed

-------------------

[ERROR  ] [2024-09-17 13:51:21] [/smtp_manager] [SMTP] blabla@unitedrobotics.group is an invalid email
[ERROR  ] [2024-09-17 13:51:21] [/smtp_manager] [SMTP] The email can not be sent because it is malformed
```

**Comment by jamendezib** [comment]
Function check_recipients has this expression: regex = r'^(\w|\.|\_|\-)+[@](\w|\_|\-|\.)+[.]\w{2,3}$'

If I am not mistaken, the last "{2,3}" in the expression means that the top-level domains can end with only 2 or 3 letters, so ".group" fails.

**Comment by jamendezib** [comment]
regex = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
This works correctly

**Comment by jamendezib** [comment]
https://github.com/RobotnikAutomation/robotnik_email/pull/8
